# Generated by Django 4.2.1 on 2023-05-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=600, verbose_name='Категория')),
                ('image', models.CharField(max_length=600, verbose_name='Ссылка на иллюстрацию')),
                ('title', models.CharField(max_length=600, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
    ]
