# Generated by Django 4.2.1 on 2023-05-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0002_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Иллюстрация'),
        ),
    ]
